# fly.toml app configuration file generated for avianvisitors-ebird on 2026-07-20T12:28:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avianvisitors-ebird'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '512mb'
